spring:
  application:
    name: booking-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

server:
  port: 9002

logging:
  level:
    com.snapserve.booking: INFO
  include-application-name: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info

user:
  service:
    url: ${USER_SERVICE_URL:http://user-service:9001}

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://notification-service:9003}
