spring:
  data:
    mongodb:
      auto-index-creation: false

logging:
  level:
    com.snapserve.user: WARN
  include-application-name: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
