spring:
  data:
    mongodb:
      auto-index-creation: false

server:
  shutdown: graceful

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL}

logging:
  level:
    com.snapserve.user: WARN
  include-application-name: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
