spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: 9000

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
