[versions]
spring-boot  = "4.0.3"
spring-cloud = "2025.1.1"
jjwt         = "0.12.6"
lombok       = "1.18.42"
spotless     = "7.0.2"

[libraries]
spring-boot-starter-web          = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-security     = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-mail         = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-boot-starter-thymeleaf    = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-boot-starter-actuator     = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-test         = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-cloud-gateway-mvc         = { module = "org.springframework.cloud:spring-cloud-starter-gateway-mvc" }
jjwt-api                         = { module = "io.jsonwebtoken:jjwt-api",     version.ref = "jjwt" }
jjwt-impl                        = { module = "io.jsonwebtoken:jjwt-impl",    version.ref = "jjwt" }
jjwt-jackson                     = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
lombok                           = { module = "org.projectlombok:lombok",     version.ref = "lombok" }

[plugins]
spring-boot     = { id = "org.springframework.boot",        version.ref = "spring-boot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version = "1.1.7" }
spotless        = { id = "com.diffplug.spotless",           version.ref = "spotless" }
