server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: booking-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        errorDecoder: com.snapserve.bookingservice.config.FeignErrorDecoder
