spring.application.name=auth-service

spring.data.mongodb.uri=mongodb+srv://abijithsuresh:REDACTED@cluster0.bzx9a.mongodb.net/AuthDb?retryWrites=true&w=majority&appName=Cluster0

server.port=9000

# Eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}
